### ISSUE TITLE
3.2.0 issue inserting new translations

### ISSUE THREAD

**Issue by frankykubo** [marhali/easy-i18n#110]
Hello,

I have a Vue project, running in JetBrains PHP storm and I am using your plugin for a while. My language files are located as in picture below:

![structure](https://user-images.githubusercontent.com/50501921/164625686-a4615309-81de-4e0d-a248-f7d6ab37b9d0.png)

In plugin config, I have settings set as:

![settings](https://user-images.githubusercontent.com/50501921/164625906-d9818e39-25fc-4b2b-8ba8-d7f98f06119f.png)

Everything works fine, I can see the structure easily in plugin page, but today I found out an issue.
I tried to insert new value within plugin page, by clicking on + icon and specifying path.

**Problem:**
Value was inserted to json as wanted, in alphabethical mode BUT one value was REMOVED from original file. So I suppose, it REPLACES the value at the given position instead of APPENDING the value at the given position.

Version of the plugin: 3.2.0
Version of PHP Storm: 2021.3.2, Build #PS-213.6777.13, built on January 14, 2022
PHP Storm Runtime version: 11.0.13+7-b1751.24 amd64
PHP Storm VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by marhali** [comment]
Could not reproduce this issue. In my setup values are properly added or overriden if the key already exists. 
Could you provide example files and a step-by-step list to reproduce the issue? 

BTW: The plugin overwrites the entire file as soon as a change is made. So there are no partial changes within the file.

Thanks 😃

**Comment by frankykubo** [comment]
I've had experimental version of PHPStorm, which was probably defect, so I did reinstall to stable version and it works well. Thank you for your response.
