### ISSUE TITLE
[Feature Request] automatically fill in existing translations in the "Add Translation" window

### ISSUE THREAD

**Issue by SIMULATAN** [marhali/easy-i18n#120]
Whilst this feature would kind of misuse the name of the panel, it would be helpful to quickly modify existing translations without having to use the panel.

Speaking of panel, when pressing "enter" after editing a field to confirm the edit, it resets the search results and displays everything again which is annoying if you only want to, say, edit the formatting of a specific translation in all languages. If this is still wanted behaviour, could you maybe introduce a setting for this?

**Comment by marhali** [comment]
Can you confirm that this behavior still occurs with version 4.0.0?
Thanks in advance.

**Comment by marhali** [comment]
> Just tested it with v4.0.0 and it still occurs. ![version](https://user-images.githubusercontent.com/63104422/166969533-3d8da998-9fad-47d2-802e-6be862c1482f.png)
> 
> Gif: ![gif](https://user-images.githubusercontent.com/63104422/166969363-44c3cdf9-1041-4273-b45b-ce09ff865c61.gif)

This should have been fixed with v4.0.1
