### ISSUE TITLE
[Feature Request]  Disable Auto-Formatter

### ISSUE THREAD

**Issue by alberto-bortolato** [marhali/easy-i18n#121]
the auto-formatter don't get the same result with the project formatter when i add a new value, i want to disable the auto-formatter

**Comment by marhali** [comment]
Changes to the formatting are subject to the file-specific parser. If a parser does not follow the recommended settings, please let me know.

**Comment by marhali** [comment]
Might be resolved with release v4.0.1. Release candidate is under the way.
