### ISSUE TITLE
split .json files under nested directories not recognized

### ISSUE THREAD

**Issue by viajes2020** [marhali/easy-i18n#124]
Hello, thank you for your plugin. It's great help me, thanks a lot.

Would it be possible to support split .json files under nested directories?

for example, my file directories is like this:
```
locales:
  en-US:
    common.json
    views:    ----> views is a directory
        child.json
  zh-CN:
    common.json
    views:
        child.json
```

here is my config:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/35365161/167083504-ea43024a-92d3-4326-bb20-a7a740c4480e.png">

it's just Identify common.json，but child.json is not。

<img width="674" alt="image" src="https://user-images.githubusercontent.com/35365161/167083665-509f13df-6e1a-4d13-8bf6-d6417bad1b8b.png">

Is there any way to fix it? 

Thanks

**Comment by viajes2020** [comment]
> 

nice work 👍

**Comment by faragos** [comment]
I have a monorepo with 2 Angular projects. I would love this feature 👍 Otherwise I always need to switch.
