### ISSUE TITLE
Newline at the end of each json file

### ISSUE THREAD

**Issue by PaulTondeur** [marhali/easy-i18n#128]
It would be great if this plugin could keep/add the newline at the end of each json file. Whenever I save a file manually, intellij already adds that for me, but when this plugin changes a json file, it removes all trailing newlines and I end up manually spending time on it to set that right again. Which is ofcourse a bit of an annoyance while the plugin is furthermore a fantastic way of managing translations.

**Comment by DatzAtWork** [comment]
The feature should depend on Settings > Editor > General > On Save
![grafik](https://user-images.githubusercontent.com/37868477/168958906-0c40400f-2644-4800-81bc-9650e868170e.png)

**Comment by PaulTondeur** [comment]
That would make sense indeed
