### ISSUE TITLE
Multiples namespace

### ISSUE THREAD

**Issue by sawa-ko** [marhali/easy-i18n#137]
Actually I see that the plugin only allows 1 namespace, and my problem is that I have several namespaces, for example, they have this format:

![image](https://user-images.githubusercontent.com/56084970/173161101-8638124e-6d74-47d2-a4d9-3d93cf6db9f6.png)

Which in directory routing would be:
```
locales/es-ES/listeners/commands/denied.json
```

Is it possible to achieve that or is there an option to do it and I have not realized it?

**Comment by kaname-png** [comment]
@marhali any news?
