### ISSUE TITLE
Compatibility with 2022.2 EAP 

### ISSUE THREAD

**Issue by flozdra** [marhali/easy-i18n#144]
Hi,

I am currenlty using the new 2022.2 EAP version, but the plugin is not available.
Do you make releases for EAP versions ? Or do I have to wait for the next stable version 2022.2 ?

Thanks in advance 😁

**Comment by pixelass** [comment]
2022.2 is stable: 
I'm using:

```
WebStorm 2022.2
Build #WS-222.3345.108, built on July 22, 2022)
```

Neither the tab, the hover action nor the context-actions are showing.

In the Plugins section of Webstorm I get this warning:

<img width="412" alt="Screen Shot 2022-07-27 at 08 09 40" src="https://user-images.githubusercontent.com/1148334/181173881-5d21a6db-69cc-465f-ae2f-5caff37e4ae5.png">
