### ISSUE TITLE
Setting for i18n plugin din't stay after restart or quit

### ISSUE THREAD

**Issue by pronovaso** [marhali/easy-i18n#164]
Hi.

I don't know why. I have last version of Webstorm and plugin. But if I change any checkbox value, after reboot or quit these checkbox are in default.

**Comment by marhali** [comment]
Could you please specify which checkbox does not persist it's state?

**Comment by pronovaso** [comment]
> Could you please specify which checkbox does not persist it's state?

All. If I check or uncheck any checkbox, after quit or restart are all in default.Other like path or preview locale works fine.
