### ISSUE TITLE
Sort translation keys alphabetically always set to true when reopening IDE

### ISSUE THREAD

**Issue by DavicVictor** [marhali/easy-i18n#186]
**Here are information you might need :**

IntelliJ IDEA 2022.2 (Ultimate Edition)
Build #IU-222.3345.118, built on July 26, 2022
Runtime version: 17.0.3+7-b469.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
Non-Bundled Plugins:
    de.marhali.easyi18n (4.2.3)
Kotlin: 222-1.7.10-release-334-IJ3345.118

I unchecked "Sort translation keys alphabetically" option yesterday and applied changes. Today after opening IntelliJ I see that this option is checked again and after adding a translation key my language files have been sorted alphabetically.

**Comment by marhali** [comment]
Reproduced, thanks!
