### ISSUE TITLE
.properties files not working

### ISSUE THREAD

**Issue by Raptor05** [marhali/easy-i18n#190]
I want to use the plugin for my SAPUI5 development. But unfortunately the i18n files are not recognized by the plugin. 
**My settings:**
- File structure: Single Directory / Properties / *.properties
- Consider subdirectories: false
- Sort translation: false
- Key delimeters: ":" "." "_" "_" (default)
- Default namespace:
- Preview locale: en
- Escape section delimeter: true
- Editor code assistance: true
- Always fold: false

**The file names are like this:**
i18n.properties
i18n_de.properties
i18n_en.properties

**The content of the files is like this:**
key=value

If I'm saving this, the tree & table view are empty. If I add a new translation, all content from the files is deleted and only the new translation has been added. When I add another translation, it overwrites the first one.

I also tried the example files from the Git Repository, but they are also not recognized.

Do you have an idea?

**Comment by marhali** [comment]
Reproduced. Thanks!
