### ISSUE TITLE
Select several specific files into settings

### ISSUE THREAD

**Issue by RomanBorisov** [marhali/easy-i18n#191]
For example, I have 10 files with translations, I add keys manually in only 2 files, and when I need to add a new translation, I need to scroll through the list of all available languages to find the ones I need, and at the same time, the keys for other languages are filled with empty values. 
Пожалуйста, добавьте возможность выбора нескольких конкретных файлов в настройках плагина, как на скрине 1
![image](https://user-images.githubusercontent.com/36147115/198218027-d3abb088-56ba-4e28-93eb-6a635db403a7.png)
![image](https://user-images.githubusercontent.com/36147115/198218209-067b62d0-09f6-494d-97c5-707d6935eeab.png)
![image](https://user-images.githubusercontent.com/36147115/198218339-92b066d7-6fcc-4f46-ad9f-bc8f4ceb4874.png)

**Comment by marhali** [comment]
Adding regex for more complex pattern matching. 
Fallback to simple wildcard matching should be still possible to be compatible with existing settings.
