### ISSUE TITLE
Latest Version seems to be incompatible with Rider 2022.3 EAP

### ISSUE THREAD

**Issue by vicr123** [marhali/easy-i18n#200]
In the release notes for v4.3.0, support was apparently added for platform version 2022.3, however Rider claims that the plugin is incompatible:

![image](https://user-images.githubusercontent.com/7380161/201470177-40ed06cb-1561-4c70-b30f-5625125e1925.png)

Maybe gradle.properties needs to be updated so pluginUntilBuild = 223.*?

**Comment by mirec75** [comment]
same problem in WebStorm 2022.3
Build #WS-223.7571.168, built on November 28, 2022
![image](https://user-images.githubusercontent.com/50924731/205888655-dd703714-82f5-40a7-9b07-8d1028800505.png)
![image](https://user-images.githubusercontent.com/50924731/205889138-a7b9cb5a-4888-4860-a55e-2ba66a343bc1.png)
