### ISSUE TITLE
Problems editing existing resource bundle

### ISSUE THREAD

**Issue by lbreuss** [marhali/easy-i18n#23]
Hallo Marcel

nice plugin, but I'm having troubles using it with our (existing) project.

We already have a resource bundle of en.json, de.json, fr.json populated, and I would like to edit these with the plugin. File format is correct so far.

- The plugin shows all existing keys red, and one column per language, but no values at all.
- Adding an entry, it is inserted correctly into the files. key shows black (probably means "complete set of values"). I can further edit key and values, everything fine. It even sorts the entry correctly in between the red keys.
- I'm not able to edit the red keys (right click has no effect), or set a value into the empty values (values are not kept)

Does the plugin somehow keep track of keys it has added itself? aatest added by plugin, looks good, but other keys are not handled / handled well.

```
{
  "aatest": "sdfg",
  "application.name": "My Application",
  "application.name.short": "App",
  "attribute.key": "Value"
}
```
 -- edited for more example data

**Comment by marhali** [comment]
Hello Leo,
the plugin uses nested json objects for keys which include one or more dots.
For example:
```
{
  "aatest": "sdfg",
  "application.name": "My Application"
}
```

becomes
```
{
  "aatest": "sdfg",
  "application": {
    "name": "My Application"
  },
}
```

EasyI18n does not support nested keys within one string literal.

**Comment by lbreuss** [comment]
Hi Marcel
Thanks for the information. So I am using the [Any to Json](https://plugins.jetbrains.com/plugin/16055-any-to-json) plugin now to "prettify" things. I suppose it generates a valid json. 
```
{
  "aatest": "sdfg",
  "application": {
    "name": [
      "My Application",
      {
        "short": "App"
      }
    ]
  },
  "attribute": {
    "key": "Value"
  }
}
```
Now Easy i18n throws an exception. Seems like the array thingy is not handled.
```
java.lang.UnsupportedOperationException: JsonObject
	at com.google.gson.JsonElement.getAsString(JsonElement.java:179)
	at de.marhali.easyi18n.util.JsonUtil.readTree(JsonUtil.java:81)
	at de.marhali.easyi18n.io.implementation.JsonTranslatorIO.lambda$read$0(JsonTranslatorIO.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:814)
	at de.marhali.easyi18n.io.implementation.JsonTranslatorIO.read(JsonTranslatorIO.java:36)
	at de.marhali.easyi18n.service.DataStore.reloadFromDisk(DataStore.java:82)
	at de.marhali.easyi18n.ui.dialog.SettingsDialog.showAndHandle(SettingsDialog.java:45)
	at de.marhali.easyi18n.ui.action.SettingsAction.actionPerformed(SettingsAction.java:24)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAware$5(ActionUtil.java:273)
```

**Comment by marhali** [comment]
I think the problem is the array value on "application.name". EasyI18n does not know how to handle that. Better approach would be:
```
{
  "aatest": "sdfg",
  "application": {
    "name": "My Application",
    "shortName": "App"
  },
}
```

**Comment by marhali** [comment]
TODO: add support for array values on i18n keys
