### ISSUE TITLE
Ide Error Report:AWT events are not allowed inside write action

### ISSUE THREAD

**Issue by LengGeng** [marhali/easy-i18n#232]
>AWT events are not allowed inside write action: sun.awt.PeerEvent

*Frequently report errors without affecting use*

**Comment by giolf** [comment]
+1 im quite annoyed that on each webstorm update the plugin crash

**Comment by dawnofclarity** [comment]
See the same in IntelliJ anytime the source files are refreshed (e.g. via Git change branch, etc)

java.lang.Throwable: AWT events are not allowed inside write action:
java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.intellij.openapi.application.impl.FlushQueue$$Lambda$429/0x00000008005f7a20@71e6911f,notifier=null,catchExceptions=false,when=1676550421382] on sun.awt.X11.XToolkit@60839c95
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.impl.NoSwingUnderWriteAction.lambda$watchForEvents$0(NoSwingUnderWriteAction.java:19)
	at com.intellij.ide.IdeEventQueue.runCustomProcessors(IdeEventQueue.java:503)

After a few of these, I need to restart IJ, as other things start to go bang...

**Comment by marhali** [comment]
Should have been fixed with release <kbd>v4.1.1</kbd>
