### ISSUE TITLE
Webstorm Freezes after adding Key

### ISSUE THREAD

**Issue by derHodrig** [marhali/easy-i18n#234]
I use this plugin with vue i18n. In first place, this plugin works just like a charm <3

But after adding a Key to the de-DE.json, the whole IDE freezes. The task manager shows some CPU usage but nothing happens in the IDE. After restarting the IDE, everything works fine until adding another key to the file.

<details>
  <summary>My Plugin options:</summary>
  
  ![image](https://user-images.githubusercontent.com/53934248/216459947-8d75c286-56fd-4610-be29-1e52e49247b6.png)
  
</details>

<details>
  <summary>The JSON File:</summary>
  
  ![image](https://user-images.githubusercontent.com/53934248/216460007-0b11340b-e243-405a-98aa-09ce4d2e3474.png)
  
</details>

PS: I just noticed, directly after restart I could add keys to the File but then after saving I got the `AWT events are not allowed inside write action` Error, which is linked to: https://github.com/marhali/easy-i18n/issues/232

**Comment by marhali** [comment]
Should have been fixed with release <kbd>v4.1.1</kbd>
