### ISSUE TITLE
i18n suggestion at kotlin code does not work

### ISSUE THREAD

**Issue by Kobins** [marhali/easy-i18n#29]
The title says it all.

![image](https://user-images.githubusercontent.com/34197983/125902304-07a3c5a4-90de-4c67-9afc-7363ebb92897.png)
suggestion at Java code 

![image](https://user-images.githubusercontent.com/34197983/125902308-d88c07e0-97cd-4e62-bea4-3ef813b73566.png)
suggestion at Kotlin code

**Comment by marhali** [comment]
Kotlin needs own annotator / completion provider because this language uses dedicated PsiElements for literals.

**Comment by Kobins** [comment]
> Kotlin needs own annotator / completion provider because this language uses dedicated PsiElements for literals.
> Waiting for an external ticket to be resolved. Tracking: [JetBrains/intellij-platform-plugin-template#154](https://github.com/JetBrains/intellij-platform-plugin-template/issues/154)

I see the tracking issue is resolved, will this fix this bug too?

**Comment by marhali** [comment]
Yes :), support has been added in upcoming release [v1.4.0](https://github.com/marhali/easy-i18n/releases/tag/v1.4.0)
