### ISSUE TITLE
Please update support

### ISSUE THREAD

**Issue by ouedyan** [marhali/easy-i18n#291]
<img width="479" alt="Screenshot 2023-07-28 at 00 16 14" src="https://github.com/marhali/easy-i18n/assets/61683979/0fa90e39-c8b5-4483-be06-5710a9f70b4b">

Using WebStorm 2023.2, Build #WS-232.8660.143, built on July 21, 2023
Plugin Version 4.4.1

**Comment by ningkexin** [comment]
@ouedyan I repackaged it for temporary use: [v4.4.2](https://github.com/marhali/easy-i18n/issues/296#issuecomment-1687339927)

**Comment by ouedyan** [comment]
Thanks @ningkexin
