### ISSUE TITLE
Support split files

### ISSUE THREAD

**Issue by konradbartecki** [marhali/easy-i18n#4]
Hey, thank you for your plugin.
Would it be possible to support split .json files with nested keys?
Use case example: https://github.com/konradbartecki/Manta/tree/dev/i18n

**Comment by marhali** [comment]
Added basic support for splitted / moduarlized json files. See latest release [v1.1.0](https://github.com/marhali/easy-i18n/releases/tag/v1.1.0)

# Example Structure
(`lang` folder needs to be specified via plugin configuration)
```yml
lang:
  de:
    user.json
    account.json
  en:
    user.json
    account.json
```
