### ISSUE TITLE
Sorting and formating JSON's

### ISSUE THREAD

**Issue by napalmpapalam** [marhali/easy-i18n#41]
When I'm deleting some key or editing it in plugin window it sorting JSON keys alphabetily, removes quotes that surrounds numbers, can you add please option to not to change this ? I really appreciate for extention, but this thing very annoying, thx!

**Comment by napalmpapalam** [comment]
And update please plugin for new 2021.2 version of webstorm plz )

**Comment by marhali** [comment]
For update to 2021.2 see #43.

The plugin always sorts the keys alphabetically. 
Could you please provide more information about the problem: `removes quotes that surrounds numbers`?
For example provide the translation file before and after the plugin has updated it.

If you want to use `"` characters they need to be escaped inside the json file like: `"numbered": "\"12\""`

**Comment by napalmpapalam** [comment]
> The plugin always sorts the keys alphabetically.

I mean this: I have a big JSON that was wrote before me, and it doesn't sorted by alp. but when I add new key through plugin it resorts all my source json, and i have 1k+ changes, can it be optional? Just add key and that's it?

> Could you please provide more information about the problem

I'm talking about this
![image](https://user-images.githubusercontent.com/47495186/127305092-222556aa-a378-468a-95b6-b7cd7d54a87c.png)

**Comment by napalmpapalam** [comment]
![image](https://user-images.githubusercontent.com/47495186/127305296-97812dbd-9116-4b38-8997-7b447efd44f5.png)

**Comment by napalmpapalam** [comment]
> For update to 2021.2 see #43. 
Can u please release new version ? Or where can I get build ?

**Comment by marhali** [comment]
Yes, the plugin always sorts the keys alphabetically. You need to commit these changes one time. After that it will only change the updated keys.

For the release see the [releases tab](https://github.com/marhali/easy-i18n/releases/tag/v1.4.1) or wait until JetBrains approves the auto update via IDE.

**Comment by napalmpapalam** [comment]
I think that it will be helpful if sorting can be optional

**Comment by Jasonizl** [comment]
having sort be optional would be awesome!
