### ISSUE TITLE
Unity *.meta files recognized as *.properties files

### ISSUE THREAD

**Issue by achimmihca** [marhali/easy-i18n#5]
This plugin seems nice and I want to use it to translate a Unity3D project because I use properties files in my Unity3D project.

However, it seems that the *.meta files that Unity creates for every "normal" file are also considered as properties file by this plugin.

Example: I have `message.properties` and `messages_de.properties`. Unity creates for these `message.properties.meta` and `messages_de.properties.meta` to store some additional information.
Now, the Easy-i18n plugin displays all 4 files in the "Table view". Instead, it should ignore the *.meta files.

**Comment by marhali** [comment]
Added configuration option to filter translation files via regex. See release [v1.1.0](https://github.com/marhali/easy-i18n/releases/tag/v1.1.0)
