### ISSUE TITLE
UTF-8 properties files

### ISSUE THREAD

**Issue by achimmihca** [marhali/easy-i18n#6]
Properties files are typically encoded in a "simple" ASCII format and unicode characters are escaped.
However, I have a custom plugin to use properties files with Unity3D. Thereby the properties files are encoded as UTF-8 for simplicity (it is simpler for me when working with other text editors, when searching, etc.).

I noticed that Easy-i18n is changing the UTF-8 encoded characters in my files to the escaped version. Example: `ü` becomes `\u00FC`

Is there an option to use UTF-8 instead?

**Comment by achimmihca** [comment]
I also noticed that some `\n` newlines were removed from my files. This should not happen.
Could be related to the UTF-8 issue.

**Comment by marhali** [comment]
Should have been fixed now with latest release [v1.1.0](https://github.com/marhali/easy-i18n/releases/tag/v1.1.0)
