### ISSUE TITLE
Support Flutter Locale Files (.arb)

### ISSUE THREAD

**Issue by marhali** [marhali/easy-i18n#64]
JsonIOStrategy can be used. Just add <kbd>.arb</kbd> as alternative file type.

**Comment by aliyazdi75** [comment]
Hi @marhali Thanks for the plugin.
It doesn't seem to work correctly for flutter. It shows the description string, not the correct translation string. For example, if you load this localization from flutter [gallery](https://github.com/flutter/gallery/blob/master/lib/l10n/intl_en.arb), it doesn't work correctly.

**Comment by marhali** [comment]
Hello the file could be read successfully. However, the plugin does not distinguish between metadata and real data. Maybe it is not the best solution for Flutter. Try a look at https://plugins.jetbrains.com/plugin/13666-flutter-intl
