### ISSUE TITLE
1.6 is not working

### ISSUE THREAD

**Issue by LifeIsStrange** [marhali/easy-i18n#65]
Throw an expression about GSON type mismatch
I rolled back to 1.5.1 in the meantime (sorry don't have the time to reproduce and paste here the exception message)

**Comment by marhali** [comment]
It would be great if an error message could be provided.

**Comment by marhali** [comment]
Could not reproduce this issue. Please check if your translation file is properly formatted and no other files are in the specified directory.

**Comment by marhali** [comment]
Closing this ticket now because it is based on an outdated version. If the error occurs on the newest version please open a new issue with the exception stack trace.
