### ISSUE TITLE
Consider supporting JSON5

### ISSUE THREAD

**Issue by LifeIsStrange** [marhali/easy-i18n#66]
The library I use (VueI18n) supports the JSON5 format (a no-nonsensical JSON format that is actually made for humans), so it would be really nice if this extension could support reading and editing JSON5 files :)
https://json5.org/

**Comment by marhali** [comment]
Consider adding https://github.com/falkreon/Jankson as experimental json processor.

**Comment by marhali** [comment]
Jankson does not work well with Windows line-breaks. Skipping this topic for now. The market for JSON5 processors on Java is really rare right now. Maybe in the future there might be a good solution.

**Comment by marhali** [comment]
Consider using https://github.com/Synt4xErr0r4/json5
