### ISSUE TITLE
Keyboard shortcut seems not working

### ISSUE THREAD

**Issue by john8329** [marhali/easy-i18n#71]
When I type cmd-n for creating a translation, it shows an empty menu and doesn't do what the + button does. Is it by design?
I think it'd be great to have keyboard shortcuts for managing entries.

**Comment by marhali** [comment]
ATM there is no <kbd>cmd+n</kbd> action to create an translation. You can create one by using the <kbd>+</kbd> button inside Easy I18n tool-window or type an translation key inside an file like: `$t('some.translation.key')`. After that you can use the <kbd>cmd+click</kbd> (go to declaration) action to open that translation. This action supports create & modify.

**Comment by john8329** [comment]
Got it, will try as you say. Perhaps it'd be good to remove the menu that appears with cmd+n, as it may be misleading (if possible). Feel free to close the issue if you wish.

**Comment by marhali** [comment]
I am open for adding a function to the <kbd>cmd+n</kbd> command but unfortunately I don't know which menu you mean. Inside code, translation tool-window or other place?

**Comment by john8329** [comment]
In the bottom area where there's the translation tree. I'm already getting used to doing it in the code, and indeed it's faster but sometimes it has to be done there
<img width="502" alt="Screenshot 2022-01-06 at 11 24 08" src="https://user-images.githubusercontent.com/42315498/148368403-4e57e51c-dc2b-4ff2-87bb-adf207284b88.png">
.

**Comment by marhali** [comment]
Thank you for your detailed explanation. I will take a look into it 😀

**Comment by marhali** [comment]
Upcoming release will include full keyboard shortcut support.
