### ISSUE TITLE
Support arrays

### ISSUE THREAD

**Issue by john8329** [marhali/easy-i18n#75]
Currently if I try to load a translation file that includes an array (needed for the UI framework localization), the plugin crashes. It'd be nice to handle them, if possibile, BabelEdit does that without any problem. Otherwise it's also okay to not support them in the UI but still load and save translations.

Thanks

**Comment by marhali** [comment]
There is already support for array values on yaml, json and properties files. Examples can be found [here](https://github.com/marhali/easy-i18n/tree/main/example).
Could you provide more information?

**Comment by john8329** [comment]
Interesting, I see the examples cover them. I was misled by an old issue in the tracker. The problem here is that loading my JSON produces an exception:
```
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:911)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:870)
	at de.marhali.easyi18n.io.json.JsonIOStrategy.lambda$read$0(JsonIOStrategy.java:80)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:839)
	at de.marhali.easyi18n.io.json.JsonIOStrategy.read(JsonIOStrategy.java:62)
	at de.marhali.easyi18n.DataStore.loadFromPersistenceLayer(DataStore.java:74)
	at de.marhali.easyi18n.dialog.SettingsDialog.showAndHandle(SettingsDialog.java:54)
	at de.marhali.easyi18n.action.SettingsAction.actionPerformed(SettingsAction.java:24)
```

I can provide you the JSON privately if you need.
Thanks (btw I tried other i18n solutions and so far this is the best for Angular, keep up the good work).

**Comment by marhali** [comment]
It seems that a translation file cannot be loaded. Please check if all files define at least one empty object (<kbd>{}</kbd>). 

The error can also occur if there are files other than translations in the folder. In this case you can set a rule in the settings to load only relevant files. 

If the problem persists, feel free to send me the JSON files. I will then take a look at them.

**Comment by john8329** [comment]
There are elements that define an array rather than an Object, and I suspect that's the cause. I've sent you the file by email.

**Comment by marhali** [comment]
I have not received any email. See my web page for an address. ([marhali.de](https://marhali.de)). It will not work with an array as root data type. Are there constellations in Angular with arrays as root data type?

**Comment by john8329** [comment]
Apologies, I picked the one I saw on your Github account. No, as far as I know there's no need to have arrays at root. Here it's necessary because the PrimeNG library requires a specific object structure for their i18n data, and I'm storing it in the same JSON that holds all the other language strings.

**Comment by marhali** [comment]
Okay I have tested the provided file. Arrays work for keys such as <kbd>primeng.monthNamesShort</kbd>. An example translation would look like: <kbd>!arr[Jan;Feb;Mar;Apr,...]</kbd>. I did not get any errors.

Are there any other files in the folder, such as metafiles? If so, they must be excluded in the EasyI18n configuration. See also #23.

**Comment by john8329** [comment]
Ok, my bad, the error must have confused me when I did the isolated test. Apparently the problem was caused by a `.DS_Store` file in the i18n directory, which is automatically generated by macOS. I removed it and it seems to work now. I think the plugin should ignore dot files by default, do you agree?

**Comment by marhali** [comment]
I agree with you there. For this reason a regex rule can be applied to read only relevant files.
Ignoring by default would lead to more confusion to the user because some files would be ignored.

However I can optimize the exception which will be shown if invalid files were found. See #76.

You can configure EasyI18n to only read json files. Just apply the following rule as the **Translation File Pattern**: <kbd>.*.json</kbd>

**Comment by john8329** [comment]
Excellent, thanks. It'd be nice to have the glob pattern written under the field as an example or something intuitive for the user (I'd expect to write `*.json` rather than with the initial dot, this might help). Also keep in mind that .DS_Store are mac system files apps are expected to ignore, but you choose what's best here. Feel free to close the issue.
