### ISSUE TITLE
escape text problem when editing bundle properties files

### ISSUE THREAD

**Issue by Kieaer** [marhali/easy-i18n#82]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/44261958/151670955-ad50ec55-09fb-448a-9b0b-1ce501b9e2fb.gif)
Intellij resource bundle editor is broken at long time and i finding alternative.

**Comment by marhali** [comment]
The plugin should already handle character escaping. I could reproduce some weird behaviour with the character: ￦.
After enabling the **Transparent native-to-ascii conversion** checkbox under <kbd>Settings / Editor / File Encodings</kbd> it worked correctly. 

![image](https://user-images.githubusercontent.com/14369479/151675887-c7331810-999b-4b81-a86c-bd54edc90a10.png)

If the problem persists please provide:
- encoding which was used for the properties files
- example properties values to reproduce this issue

**Comment by marhali** [comment]
Okay could reproduce the escaping issue when using <kbd>/</kbd> inside a property value. I will take a look into it.

**Comment by marhali** [comment]
> Okay could reproduce the escaping issue when using / inside a property value. I will take a look into it.

Upcoming release will provide a fix for this 👍
